# Generated by Django 4.1.4 on 2022-12-29 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callretriver', '0002_alter_company_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='company_parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_team_child', to='callretriver.company'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_child', to='callretriver.team'),
        ),
    ]
