# Generated by Django 4.1.4 on 2022-12-29 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callretriver', '0003_alter_team_company_parent_alter_team_team_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_user_child', to='callretriver.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='team_parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_user_child', to='callretriver.team'),
        ),
    ]
