# Generated by Django 4.1.4 on 2022-12-29 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callretriver', '0004_alter_user_company_parent_alter_user_team_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='parent',
            new_name='company_parent',
        ),
    ]
